# Generated by Django 5.1.7 on 2025-05-18 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beverages', '0002_uploadmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beverages',
            name='image',
            field=models.ImageField(default='', upload_to='image'),
        ),
    ]
