# Generated by Django 5.1.7 on 2025-05-18 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beverages', '0003_alter_beverages_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beverages',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to='image'),
        ),
    ]
