# Generated by Django 5.1.7 on 2025-05-18 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beverages', '0004_alter_beverages_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadModel',
        ),
        migrations.RemoveField(
            model_name='beverages',
            name='image',
        ),
        migrations.AddField(
            model_name='beverages',
            name='imageUrl',
            field=models.CharField(default='', max_length=50),
        ),
    ]
