# Generated by Django 5.1.7 on 2025-05-18 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beverages', '0005_delete_uploadmodel_remove_beverages_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='image')),
            ],
        ),
        migrations.AlterField(
            model_name='beverages',
            name='imageUrl',
            field=models.ImageField(blank=True, default='', upload_to='image'),
        ),
    ]
