# Generated by Django 5.1.7 on 2025-05-18 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beverages', '0006_uploadmodel_alter_beverages_imageurl'),
    ]

    operations = [
        migrations.RenameField(
            model_name='beverages',
            old_name='imageUrl',
            new_name='image',
        ),
    ]
