# Generated by Django 5.1.7 on 2025-05-18 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beverages', '0007_rename_imageurl_beverages_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beverages',
            name='description',
            field=models.TextField(),
        ),
    ]
