# Generated by Django 5.1.7 on 2025-05-18 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beverages', '0008_alter_beverages_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beverages',
            name='categories',
        ),
        migrations.AddField(
            model_name='beverages',
            name='categories',
            field=models.ManyToManyField(to='beverages.beveragescategories'),
        ),
    ]
