# Generated by Django 5.1.7 on 2025-05-18 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brunch', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brunch',
            name='image',
            field=models.ImageField(blank=True, upload_to='image'),
        ),
    ]
