# Generated by Django 5.1.7 on 2025-05-20 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brunch', '0002_alter_brunch_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brunch',
            name='categories',
        ),
        migrations.AddField(
            model_name='brunch',
            name='categories',
            field=models.ManyToManyField(to='brunch.brunchcategories'),
        ),
    ]
