# Generated by Django 5.1.7 on 2025-05-20 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brunch', '0003_remove_brunch_categories_brunch_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='image')),
            ],
        ),
    ]
