# Generated by Django 5.1.7 on 2025-05-20 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brunch', '0004_uploadmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brunch',
            name='description',
            field=models.TextField(),
        ),
    ]
